name       : font-awesome-ttf
version    : 5.11.2
release    : 15
source     :
    - https://github.com/FortAwesome/Font-Awesome/archive/5.11.2.tar.gz : f4e4622b944267cbd063cb75c6b606924eea1f801bd3585075695f681cebd723
license    : OFL-1.1
component  : desktop.font
summary    : Font Awesome Free
description: |
    Font Awesome - The iconic font and CSS toolkit
install    : |
    install -D -m00644 webfonts/*.ttf -t $installdir/usr/share/fonts/truetype/fontawesome/
