name       : font-awesome-ttf
version    : 5.0.9
release    : 6
source     :
    - https://github.com/FortAwesome/Font-Awesome/archive/5.0.9.tar.gz : ddb8bea3368b6c252abb3a890eac2a220e787b57de4e1238f5bf01b36d3d8250
license    : OFL-1.1
component  : desktop.font
summary    : Font Awesome Free
description: |
    Font Awesome - The iconic font and CSS toolkit
install    : |
    install -D -m00644 web-fonts-with-css/webfonts/*.ttf -t $installdir/usr/share/fonts/truetype/fontawesome/
