name       : font-awesome-ttf
version    : 5.12.1
release    : 17
source     :
    - https://github.com/FortAwesome/Font-Awesome/archive/5.12.1.tar.gz : 218060ed286d88de951ac6d6f79677498e12db230e2313bc80644a4f50b206b6
homepage   : https://fontawesome.com
license    : OFL-1.1
component  : desktop.font
summary    : Font Awesome Free
description: |
    Font Awesome - The iconic font and CSS toolkit
install    : |
    install -Dm00644 webfonts/*.ttf -t $installdir/usr/share/fonts/truetype/fontawesome/
