name       : font-awesome-ttf
version    : 5.8.1
release    : 10
source     :
    - https://github.com/FortAwesome/Font-Awesome/archive/5.8.1.tar.gz : b0ef5da4323d277695a1335f0fbaf9aa84ff782380082179c0ad37565e110bd8
license    : OFL-1.1
component  : desktop.font
summary    : Font Awesome Free
description: |
    Font Awesome - The iconic font and CSS toolkit
install    : |
    install -D -m00644 webfonts/*.ttf -t $installdir/usr/share/fonts/truetype/fontawesome/
