name       : font-awesome-ttf
version    : 5.10.2
release    : 13
source     :
    - https://github.com/FortAwesome/Font-Awesome/archive/5.10.2.tar.gz : 67d1f38d969478e7b0bf07137833d2325b1c23281987f9a3afcd6203d726ae52
license    : OFL-1.1
component  : desktop.font
summary    : Font Awesome Free
description: |
    Font Awesome - The iconic font and CSS toolkit
install    : |
    install -D -m00644 webfonts/*.ttf -t $installdir/usr/share/fonts/truetype/fontawesome/
