name       : font-awesome-ttf
version    : 5.13.0
release    : 18
source     :
    - https://github.com/FortAwesome/Font-Awesome/archive/5.13.0.tar.gz : 37af63f2a6bdc01029f00c0c76d661a4b721c9f5cb1401a5d3b9f388d0c25f53
homepage   : https://fontawesome.com
license    : OFL-1.1
component  : desktop.font
summary    : Font Awesome Free
description: |
    Font Awesome - The iconic font and CSS toolkit
install    : |
    install -Dm00644 webfonts/*.ttf -t $installdir/usr/share/fonts/truetype/fontawesome/
