name       : font-awesome-ttf
version    : 6.1.1
release    : 27
source     :
    - https://github.com/FortAwesome/Font-Awesome/archive/refs/tags/6.1.1.tar.gz : 9a4169f7715951969c746a225eac6292be5d16ab2ae7555b62cbf0d271175822
homepage   : https://fontawesome.com
license    : OFL-1.1
component  : desktop.font
summary    : Font Awesome Free
description: |
    Font Awesome - The iconic font and CSS toolkit
install    : |
    install -Dm00644 webfonts/*.ttf -t $installdir/usr/share/fonts/truetype/fontawesome/
