name       : font-awesome-ttf
version    : 5.0.10
release    : 7
source     :
    - https://github.com/FortAwesome/Font-Awesome/archive/5.0.10.tar.gz : a2588298f516d6f894b31d1990819d0af70f4beccc3e2c364d30d813f8af4193
license    : OFL-1.1
component  : desktop.font
summary    : Font Awesome Free
description: |
    Font Awesome - The iconic font and CSS toolkit
install    : |
    install -D -m00644 web-fonts-with-css/webfonts/*.ttf -t $installdir/usr/share/fonts/truetype/fontawesome/
