name       : font-awesome-ttf
version    : 5.15.4
release    : 24
source     :
    - https://github.com/FortAwesome/Font-Awesome/archive/refs/tags/5.15.4.tar.gz : 82c301594a566277ba3cf41e037fc03ae101727d3e5d682d09e322a53937b5ed
homepage   : https://fontawesome.com
license    : OFL-1.1
component  : desktop.font
summary    : Font Awesome Free
description: |
    Font Awesome - The iconic font and CSS toolkit
install    : |
    install -Dm00644 webfonts/*.ttf -t $installdir/usr/share/fonts/truetype/fontawesome/
