name       : font-awesome-ttf
version    : 5.0.8
release    : 5
source     :
    - https://github.com/FortAwesome/Font-Awesome/archive/5.0.8.tar.gz : b404ac351ea63710496fa0f35e08e4a464d73a3fc20f25e55f1cb239987cd560
license    : OFL-1.1
component  : desktop.font
summary    : Font Awesome Free
description: |
    Font Awesome - The iconic font and CSS toolkit
install    : |
    install -D -m00644 web-fonts-with-css/webfonts/*.ttf -t $installdir/usr/share/fonts/truetype/fontawesome/
