name       : font-awesome-ttf
version    : 5.8.2
release    : 11
source     :
    - https://github.com/FortAwesome/Font-Awesome/archive/5.8.2.tar.gz : 2af21ae0de9b7232b28f1ba6fd1006f17ea2240d2e85127359ccfa0c1024f7d9
license    : OFL-1.1
component  : desktop.font
summary    : Font Awesome Free
description: |
    Font Awesome - The iconic font and CSS toolkit
install    : |
    install -D -m00644 webfonts/*.ttf -t $installdir/usr/share/fonts/truetype/fontawesome/
