name       : font-awesome-ttf
version    : 5.0.2
release    : 4
source     :
    - https://use.fontawesome.com/releases/v5.0.2/fontawesome-free-5.0.2.zip : 77c18e313e2259639444126a676c5628de61c822485f152f6610c382ab6f76ed
license    : OFL-1.1
component  : desktop.font
summary    : Font Awesome Free
description: |
    Font Awesome - The iconic font and CSS toolkit
install    : |
    install -D -m00644 web-fonts-with-css/webfonts/*.ttf -t $installdir/usr/share/fonts/truetype/fontawesome/
