name       : font-awesome-ttf
version    : 5.9.0
release    : 12
source     :
    - https://github.com/FortAwesome/Font-Awesome/archive/5.9.0.tar.gz : cfa771c26866011d8988e2de2d8ce8cd199e5b03eb58ff6dbeb1abd8049cd697
license    : OFL-1.1
component  : desktop.font
summary    : Font Awesome Free
description: |
    Font Awesome - The iconic font and CSS toolkit
install    : |
    install -D -m00644 webfonts/*.ttf -t $installdir/usr/share/fonts/truetype/fontawesome/
