name       : font-awesome-ttf
version    : 4.7.0
release    : 3
source     :
    - http://fontawesome.io/assets/font-awesome-4.7.0.zip : 8dd560347f1850ae2bb9ae13ae33fdbb44b7af00427fa15a4ed55a1a08af30bb
license    : OFL-1.1
component  : desktop.font
summary    : Font Awesome - The iconic font and CSS toolkit
description: |
    Font Awesome - The iconic font and CSS toolkit
install    : |
    install -Dm00644 fonts/fontawesome-webfont.ttf $installdir/usr/share/fonts/truetype/fontawesome/fontawesome.ttf
