name       : font-awesome-ttf
version    : 5.13.1
release    : 19
source     :
    - https://github.com/FortAwesome/Font-Awesome/archive/5.13.1.tar.gz : 26cae227514f3f77f9a43ad4e4f6a383702e08a5ec2a2fcb055cd35e033b7dd2
homepage   : https://fontawesome.com
license    : OFL-1.1
component  : desktop.font
summary    : Font Awesome Free
description: |
    Font Awesome - The iconic font and CSS toolkit
install    : |
    install -Dm00644 webfonts/*.ttf -t $installdir/usr/share/fonts/truetype/fontawesome/
