name       : font-awesome-ttf
version    : 4.6
release    : 2
source     :
    - http://fontawesome.io/assets/font-awesome-4.6.3.zip : e59dd2ee7f461a15fbc08ea8156d807b6d1401e2274701cf093ef2e5b47b0ba0
license    : OFL-1.1
component  : desktop.font
summary    : Font Awesome - The iconic font and CSS toolkit
description: |
    Font Awesome - The iconic font and CSS toolkit
install    : |
    install -D -m 00644 fonts/fontawesome-webfont.ttf $installdir/usr/share/fonts/truetype/fontawesome/fontawesome.ttf
